// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9E2EoW6_-Qixp6OUq8GisUp71Z-QSJZg',
    appId: '1:1021773923429:web:ea8d165c9d81733ac9f28c',
    messagingSenderId: '1021773923429',
    projectId: 'logbook2electricboogaloo',
    authDomain: 'logbook2electricboogaloo.firebaseapp.com',
    storageBucket: 'logbook2electricboogaloo.appspot.com',
    measurementId: 'G-8QQJXX2WXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMy1wakrpIKtCP4Y1SM6IZlpmO6TSLKDA',
    appId: '1:1021773923429:android:058024b79676d07bc9f28c',
    messagingSenderId: '1021773923429',
    projectId: 'logbook2electricboogaloo',
    storageBucket: 'logbook2electricboogaloo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl6rlis7STc6l4HbN_JX9THtaDENG6j6M',
    appId: '1:1021773923429:ios:c407a7c92d4cd2fec9f28c',
    messagingSenderId: '1021773923429',
    projectId: 'logbook2electricboogaloo',
    storageBucket: 'logbook2electricboogaloo.appspot.com',
    iosClientId: '1021773923429-mlmu0g22m9g7hkrk1p2pcv908abulac5.apps.googleusercontent.com',
    iosBundleId: 'com.electricboogaloo.logbook2electricboogaloo',
  );
}
